In [1]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,StandardScaler,LabelEncoder
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')

In [3]:
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='str')

In [5]:
data.drop(['RowNumber', 'CustomerId', 'Surname'],axis=1,inplace=True)

In [6]:
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  str
 2   Gender           10000 non-null  str
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), str(2)
memory usage: 966.1 KB

In [8]:
data.describe()

        CreditScore           Age  ...  EstimatedSalary        Exited
count  10000.000000  10000.000000  ...     10000.000000  10000.000000
mean     650.528800     38.921800  ...    100090.239881      0.203700
std       96.653299     10.487806  ...     57510.492818      0.402769
min      350.000000     18.000000  ...        11.580000      0.000000
25%      584.000000     32.000000  ...     51002.110000      0.000000
50%      652.000000     37.000000  ...    100193.915000      0.000000
75%      718.000000     44.000000  ...    149388.247500      0.000000
max      850.000000     92.000000  ...    199992.480000      1.000000

[8 rows x 9 columns]

In [12]:
## Encoding the Gender 

label_encoder_gender = LabelEncoder()

data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [14]:
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [27]:
## Applying One hot encoding to the Geography


oh_encoder_geo = OneHotEncoder()
geo_encoded = oh_encoder_geo.fit_transform(data[['Geography']])
geo_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [29]:
geo_encoded_df = pd.DataFrame(geo_encoded.toarray(),columns=oh_encoder_geo.get_feature_names_out(['Geography']))

In [30]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [31]:
data = pd.concat([data.reset_index(drop=True),geo_encoded_df],axis=1)

In [33]:
data.head()

   CreditScore Geography  ...  Geography_Germany  Geography_Spain
0          619    France  ...                0.0              0.0
1          608     Spain  ...                0.0              1.0
2          502    France  ...                0.0              0.0
3          699    France  ...                0.0              0.0
4          850     Spain  ...                0.0              1.0

[5 rows x 14 columns]

In [34]:
data.drop(['Geography'],axis=1,inplace=True)

In [35]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [36]:
 # Independent and dependent features 

X = data.drop(['EstimatedSalary'],axis=1)
y = data['EstimatedSalary']

In [37]:
X.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 12 columns]

In [38]:
y

0       101348.88
1       112542.58
2       113931.57
3        93826.63
4        79084.10
          ...
9995     96270.64
9996    101699.77
9997     42085.58
9998     92888.52
9999     38190.78
Name: EstimatedSalary, Length: 10000, dtype: float64

In [39]:
# train test and split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)

In [40]:
scaler= StandardScaler()

In [41]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [42]:
## Save the Encoders and scalers
with open('label_encoder_gender.pkl','wb') as file:
  pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
  pickle.dump(oh_encoder_geo,file)

with open('scaler.pkl','wb') as file:
  pickle.dump(scaler,file)

### ANN model training for regression problem statement

In [43]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

In [44]:
# Build the model

model = Sequential([
  Dense(64,activation='relu',input_shape=(X_train_scaled.shape[1],)),
  Dense(32,activation='relu'),
  Dense(1) ## Output
])

c:\Users\Lalit\OneDrive\Desktop\AIML\Bootcamp\30. ANN\End To End Deep Learning Project Using ANN\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [45]:
## Compile the model

model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

In [46]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [47]:
## Set up the TensorBoard

import datetime

log_dir = 'logs/fit/' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorflow_callback  = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [48]:
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [49]:
model.fit(
  X_train_scaled,y_train,
  epochs=100,
  batch_size=32,
  validation_data=(X_test_scaled,y_test),
  callbacks=[tensorflow_callback,early_stopping_callback],
  verbose = 1
  )

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 100378.0391 - mae: 100378.0391 - val_loss: 98519.8203 - val_mae: 98519.8203
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99623.9844 - mae: 99623.9844 - val_loss: 96998.7109 - val_mae: 96998.7109
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 96959.9141 - mae: 96959.9141 - val_loss: 93125.9844 - val_mae: 93125.9844
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 91763.8203 - mae: 91763.8203 - val_loss: 86724.9688 - val_mae: 86724.9688
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 84219.4062 - mae: 84219.4062 - val_loss: 78447.2734 - val_mae: 78447.2734
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 75390.1016 - mae: 75390.1016 - val_loss: 69754.3438 - val_mae: 69754.3438
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 66840.6562 - mae: 66840.6562 - val_loss: 62208.6445 - val_mae: 62208.6445
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 59852.4258 - mae: 59852.4258 - val_loss: 56593.8945 - val_mae: 56593.8945
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 54946.5703 - mae: 54946.5703 - val_loss: 53176.8867 - val_mae: 53176.8867
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 52204.9102 - mae: 52204.9102 - val_loss: 51570.2344 - val_mae: 51570.2344
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50948.4844 - mae: 50948.4844 - val_loss: 50947.8398 - val_mae: 50947.8398
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50435.2227 - mae: 50435.2227 - val_loss: 50727.1914 - val_mae: 50727.1914
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50241.8242 - mae: 50241.8242 - val_loss: 50648.9414 - val_mae: 50648.9414
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50142.2461 - mae: 50142.2461 - val_loss: 50609.1992 - val_mae: 50609.1992
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50076.7852 - mae: 50076.7852 - val_loss: 50578.7969 - val_mae: 50578.7969
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50030.3047 - mae: 50030.3047 - val_loss: 50542.1523 - val_mae: 50542.1523
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49988.9375 - mae: 49988.9375 - val_loss: 50521.2266 - val_mae: 50521.2266
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49953.1211 - mae: 49953.1211 - val_loss: 50497.7539 - val_mae: 50497.7539
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49920.2930 - mae: 49920.2930 - val_loss: 50484.1719 - val_mae: 50484.1719
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49888.1328 - mae: 49888.1328 - val_loss: 50462.5078 - val_mae: 50462.5078
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49861.9766 - mae: 49861.9766 - val_loss: 50452.6992 - val_mae: 50452.6992
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49841.4688 - mae: 49841.4688 - val_loss: 50434.8672 - val_mae: 50434.8672
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49818.8750 - mae: 49818.8750 - val_loss: 50428.2383 - val_mae: 50428.2383
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49797.0117 - mae: 49797.0117 - val_loss: 50423.5352 - val_mae: 50423.5352
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49777.9141 - mae: 49777.9141 - val_loss: 50418.1562 - val_mae: 50418.1562
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49757.7852 - mae: 49757.7852 - val_loss: 50409.9922 - val_mae: 50409.9922
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49739.3281 - mae: 49739.3281 - val_loss: 50397.5586 - val_mae: 50397.5586
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49724.7539 - mae: 49724.7539 - val_loss: 50389.6641 - val_mae: 50389.6641
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49710.7773 - mae: 49710.7773 - val_loss: 50383.0898 - val_mae: 50383.0898
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49697.4141 - mae: 49697.4141 - val_loss: 50379.3164 - val_mae: 50379.3164
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49680.8594 - mae: 49680.8594 - val_loss: 50370.9609 - val_mae: 50370.9609
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49669.3594 - mae: 49669.3594 - val_loss: 50373.0625 - val_mae: 50373.0625
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49657.8672 - mae: 49657.8672 - val_loss: 50366.4023 - val_mae: 50366.4023
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49646.1719 - mae: 49646.1719 - val_loss: 50362.9766 - val_mae: 50362.9766
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49632.7812 - mae: 49632.7812 - val_loss: 50367.1406 - val_mae: 50367.1406
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49620.2812 - mae: 49620.2812 - val_loss: 50363.4727 - val_mae: 50363.4727
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49608.4141 - mae: 49608.4141 - val_loss: 50358.6875 - val_mae: 50358.6875
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49598.2266 - mae: 49598.2266 - val_loss: 50361.2734 - val_mae: 50361.2734
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49590.8633 - mae: 49590.8633 - val_loss: 50360.1328 - val_mae: 50360.1328
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49579.9375 - mae: 49579.9375 - val_loss: 50360.5703 - val_mae: 50360.5703
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49573.1992 - mae: 49573.1992 - val_loss: 50352.0625 - val_mae: 50352.0625
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49564.5391 - mae: 49564.5391 - val_loss: 50357.3750 - val_mae: 50357.3750
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49553.0781 - mae: 49553.0781 - val_loss: 50360.9844 - val_mae: 50360.9844
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49546.1055 - mae: 49546.1055 - val_loss: 50354.6680 - val_mae: 50354.6680
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49536.5078 - mae: 49536.5078 - val_loss: 50357.9453 - val_mae: 50357.9453
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49529.1328 - mae: 49529.1328 - val_loss: 50357.7383 - val_mae: 50357.7383
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49523.2227 - mae: 49523.2227 - val_loss: 50362.7812 - val_mae: 50362.7812
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49518.5469 - mae: 49518.5469 - val_loss: 50365.1602 - val_mae: 50365.1602
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49507.8125 - mae: 49507.8125 - val_loss: 50356.9570 - val_mae: 50356.9570
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49503.6328 - mae: 49503.6328 - val_loss: 50360.3398 - val_mae: 50360.3398
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49494.9531 - mae: 49494.9531 - val_loss: 50357.1680 - val_mae: 50357.1680

In [51]:
%load_ext tensorboard

In [54]:
# %tensorboard --logdir logs/fit

In [55]:
ann_acc = model.evaluate(X_test_scaled,y_test)[1]

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50352.0625 - mae: 50352.0625

In [56]:
ann_acc

50352.0625

In [57]:
model.save('RegressionModel.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.